### ISSUE TITLE
eeprom update

### ISSUE THREAD

**Issue by christrees** [digitalrebar/edgelab#9]
So, I ran into an issue with 'fresh from factory pi'
Both the server and client boots look like the started but never 'seemed' to finish.

**Comment by christrees** [comment]
# Update EEPROM on fresh Pi4
Good practice to update the EEPROM on Pi4 before you use them.

## Recovery [from Raspberry Pi Download](https://www.raspberrypi.org/downloads/)

If your Raspberry Pi 4 will not boot, it is possible that the SPI EEPROM has become corrupted.

To check, remove the SD card, disconnect the device from power, then reconnect it. If the green LED does not flash, you will need to reprogram the EEPROM:

Download the [bootloader](https://static.raspberrypi.org/files/rpi-boot-eeprom-recovery-2019-09-10-vl805-000137ab.zip)
SHA-256: 444e0f68aa21d5b4e158259061de55738d36a1986e2ced14bb14d7af1a04881c
Extract it to an empty FAT-formatted SD card and insert it into your Raspberry Pi 4
Connect the power and wait for the green LED to flash quickly

[Pi4-EEPROM Update](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md)

[Pi4-Powerup LED TroubleShoot](https://elinux.org/R-Pi_Troubleshooting#Power_.2F_Start-up)

### Startup Issue Detail
Following [edgelab bootstrap](https://github.com/digitalrebar/edgelab/blob/master/bootstrapping.md) my Raspberry Pi server had no video output for over 30min.  I unplugged power and plugged back in, would see some activity and some of the boot on video then it would go BLANK-BLACK-SCREEN.  The LEDs were solid RED and solid GREEN.

After some time on the Pi4 forms, I found out there had been issues with the EEPROM, so I downloaded the above bootloader and updated the EEPROM.  It seemed to fix the issue.

**Comment by galthaus** [comment]
Okay - so this was for the server rpi4.  This is the exact process (plus a little more) that the clients use to set themselves into network boot mode.

**Comment by galthaus** [comment]
Yeah - we don't currently have a "fix" for this.   I'll leave this here now for searches.

**Comment by christrees** [comment]
Speaking of which... when I use the client download, it seems to kill the pi4.  Could it be you loading  an old eeprom with the client?

**Comment by galthaus** [comment]
It will leave it in a loop.  The RPIs are not very talkative.  I've found that even leaving an HDMI monitor doesn't show much during network boot.  The client image should boot the first time into raspbian, flash the prom, reboot, then it will network boot which times out after about 3-5 minutes (it is lame), and then boots back into raspbian, reflashes the prom, and reboots.  Loop forever.

I'm not sure how much HDMI display is going on when we aren't in raspbian.

**Comment by christrees** [comment]
# Client boards will STAY in slow cycle netboot

If you want to use the Pi4 with another boot SSD, you will need to run the bootloader or wait the 3 to 5 min it takes the edgeClient SSD eeprom update to try the SSD boot device.

The experiment I did was:
1. Start with a Pi4 board, no SSD, only Power, and Video.
    - No Video (expected)
    - RedLED ON - GreenLED 4 flash repeat.
2. Power off, insert BusterDesktop SSD, Power up.  
    - Normal boot Video (raspian) of about 20 sec. 
    - RedLED ON- some GreenLED flashes.
3. Power down, insert edgelabServer, Power up. A normal boot of about 60 sec. 
    - Normal boot Video (ubuntu) 
    - RedLED ON- Little or no GreenLED flashes.
4. Power down, insert edgelabClient SSD, Power up. 
    - Normal boot Video (ubuntu) (about 20 sec)
    - RedLED ON- lots GreenLED flashes.
    - RedLED ON - GreenLED ON.
    - BLANK-BLACK 
    - WAIT 3-5 min (as greg mentioned)
    - Repeats above
5. Power down, _REMOVE_ edgelabClient, NO SSD, Power up. 
    - No Video (expected)
    - RedLED ON - GreenLED ON.
6. Power down, insert BusterDesktop SSD, Power up. 
    - No Video (expected)
    - RedLED ON - GreenLED ON.
    - Wait 3-5min
    - Normal boot Video (raspian) of about 20 sec. 
    - RedLED ON- some GreenLED flashes.
    - If you power cycle, you have to wait the 3-5 min again.
7. Power down, insert bootloader SSD, Power up.
    - No Video (expected)
    - RedLED ON - GreenLED lots of dim flashes.
    - RedLED ON - GreenLED fast flash repeat.
8. Power off, insert BusterDesktop SSD, Power up.  
    - Normal boot Video (raspian) of about 20 sec. 
    - RedLED ON- some GreenLED flashes.

**Comment by christrees** [comment]
... OR I know understand what Greg was telling me ;-)

**Comment by christrees** [comment]
... also explains why Rob was mentioning tagging the 'server' and or 'clients' so you know cause if the clients can't find a server, they sort of act like dead pi... they are actually zombie pi ;-)

**Comment by christrees** [comment]
This is more of a discovery explanation that an issue.  Figure enough text is in for a future search to pick it up now.
